topics:
- name    : joy
  topic   : joy_teleop/cmd_vel
  timeout : 0.5
  priority: 10
- name    : interactive_marker
  topic   : twist_marker_server/cmd_vel
  timeout : 0.5
  priority: 8
- name    : cmd_vel
  topic   : cmd_vel
  timeout : 0.5
  priority: 1
- name    : cmd_vel_nav2d
  topic   : cmd_vel_nav2d
  timeout : 0.2
  priority: 5
- name    : cmd_vel_move_base
  topic   : cmd_vel_move_base
  timeout : 1.0
  priority: 15
locks:
- name    : e_stop
  topic   : e_stop
  timeout : 0.0
  priority: 255
